export const regions = [
    {"label": "Alabama", "option": "Alabama", "country": "United States"},
    {"label": "Alaska", "option": "Alaska", "country": "United States"},
    {"label": "Arizona", "option": "Arizona", "country": "United States"},
    {"label": "Arkansas", "option": "Arkansas", "country": "United States"},
    {"label": "California", "option": "California", "country": "United States"},
    {"label": "Colorado", "option": "Colorado", "country": "United States"},
    {"label": "Connecticut", "option": "Connecticut", "country": "United States"},
    {"label": "Delaware", "option": "Delaware", "country": "United States"},
    {"label": "Florida", "option": "Florida", "country": "United States"},
    {"label": "Georgia", "option": "Georgia", "country": "United States"},
    {"label": "Hawaii", "option": "Hawaii", "country": "United States"},
    {"label": "Idaho", "option": "Idaho", "country": "United States"},
    {"label": "Illinois", "option": "Illinois", "country": "United States"},
    {"label": "Indiana", "option": "Indiana", "country": "United States"},
    {"label": "Iowa", "option": "Iowa", "country": "United States"},
    {"label": "Kansas", "option": "Kansas", "country": "United States"},
    {"label": "Kentucky", "option": "Kentucky", "country": "United States"},
    {"label": "Louisiana", "option": "Louisiana", "country": "United States"},
    {"label": "Maine", "option": "Maine", "country": "United States"},
    {"label": "Maryland", "option": "Maryland", "country": "United States"},
    {"label": "Massachusetts", "option": "Massachusetts", "country": "United States"},
    {"label": "Michigan", "option": "Michigan", "country": "United States"},
    {"label": "Minnesota", "option": "Minnesota", "country": "United States"},
    {"label": "Mississippi", "option": "Mississippi", "country": "United States"},
    {"label": "Missouri", "option": "Missouri", "country": "United States"},
    {"label": "Montana", "option": "Montana", "country": "United States"},
    {"label": "Nebraska", "option": "Nebraska", "country": "United States"},
    {"label": "Nevada", "option": "Nevada", "country": "United States"},
    {"label": "New Hampshire", "option": "New Hampshire", "country": "United States"},
    {"label": "New Jersey", "option": "New Jersey", "country": "United States"},
    {"label": "New Mexico", "option": "New Mexico", "country": "United States"},
    {"label": "New York", "option": "New York", "country": "United States"},
    {"label": "North Carolina", "option": "North Carolina", "country": "United States"},
    {"label": "North Dakota", "option": "North Dakota", "country": "United States"},
    {"label": "Ohio", "option": "Ohio", "country": "United States"},
    {"label": "Oklahoma", "option": "Oklahoma", "country": "United States"},
    {"label": "Oregon", "option": "Oregon", "country": "United States"},
    {"label": "Pennsylvania", "option": "Pennsylvania", "country": "United States"},
    {"label": "Rhode Island", "option": "Rhode Island", "country": "United States"},
    {"label": "South Carolina", "option": "South Carolina", "country": "United States"},
    {"label": "South Dakota", "option": "South Dakota", "country": "United States"},
    {"label": "Tennessee", "option": "Tennessee", "country": "United States"},
    {"label": "Texas", "option": "Texas", "country": "United States"},
    {"label": "Utah", "option": "Utah", "country": "United States"},
    {"label": "Vermont", "option": "Vermont", "country": "United States"},
    {"label": "Virginia", "option": "Virginia", "country": "United States"},
    {"label": "Washington", "option": "Washington", "country": "United States"},
    {"label": "West Virginia", "option": "West Virginia", "country": "United States"},
    {"label": "Wisconsin", "option": "Wisconsin", "country": "United States"},
    {"label": "Wyoming", "option": "Wyoming", "country": "United States"},
    {"label": "Alberta", "option": "Alberta", "country": "Canada"},
    {"label": "British Columbia", "option": "British Columbia", "country": "Canada"},
    {"label": "Manitoba", "option": "Manitoba", "country": "Canada"},
    {"label": "New Brunswick", "option": "New Brunswick", "country": "Canada"},
    {"label": "Newfoundland and Labrador", "option": "Newfoundland and Labrador", "country": "Canada"},
    {"label": "Northwest Territories", "option": "Northwest Territories", "country": "Canada"},
    {"label": "Nova Scotia", "option": "Nova Scotia", "country": "Canada"},
    {"label": "Nunavut", "option": "Nunavut", "country": "Canada"},
    {"label": "Ontario", "option": "Ontario", "country": "Canada"},
    {"label": "Prince Edward Island", "option": "Prince Edward Island", "country": "Canada"},
    {"label": "Quebec", "option": "Quebec", "country": "Canada"},
    {"label": "Saskatchewan", "option": "Saskatchewan", "country": "Canada"},
    {"label": "Yukon", "option": "Yukon", "country": "Canada"},
    {"label": "Other", "option":"Other"}
];

export const countries = [
    {"label": "United States", "option": "United States"},
    {"label": "Canada", "option": "Canada"},
    {"label": "Other", "option": "Other"}
];